name: build

on: [push, pull_request]

jobs:
  build:
      name: Publish script
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm run build
      - name: Upload scripts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
