name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
      name: Publish script
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload scripts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/script.user.js
          tag: ${{ github.ref }}
          overwrite: true
